### ISSUE TITLE
Cannot compile for windows

### ISSUE THREAD

**Issue by AlexShemeshWix** [bouk/monkey#10]
Hi
Im using your awesome library in my project.
I have a problem with it.
Im on Mac OS 10.12.5 (16F73)
go version go1.8.3 darwin/amd64
I also tried go 1.7 - same result
It wont compile for windows architecture

I do:
`CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o my-windows-amd64`

and i get response:

```
github.com/wixplosives/c3-cli/vendor/github.com/bouk/monkey
vendor/github.com/bouk/monkey/replace_unix.go:14: undefined: syscall.Mprotect
vendor/github.com/bouk/monkey/replace_unix.go:14: undefined: syscall.PROT_READ
vendor/github.com/bouk/monkey/replace_unix.go:14: undefined: syscall.PROT_WRITE
vendor/github.com/bouk/monkey/replace_unix.go:14: undefined: syscall.PROT_EXEC
vendor/github.com/bouk/monkey/replace_unix.go:20: undefined: syscall.Mprotect
vendor/github.com/bouk/monkey/replace_unix.go:20: undefined: syscall.PROT_READ
vendor/github.com/bouk/monkey/replace_unix.go:20: undefined: syscall.PROT_EXEC
```

**Comment by SammyROCK** [comment]
I'm having the same problem.
Sadly this project is made for Unix based systems, Windows does not have those syscall functions.

**Comment by AlexShemeshWix** [comment]
Figured it out. I wrote TestKit kind of object that was using monkey/patch.  It was in file that was not ending with _test.go. 
On other side - its a shame that testing wont run on windows.
