### ISSUE TITLE
unknown method and weird behavior

### ISSUE THREAD

**Issue by soldiershen** [bouk/monkey#5]
Great framework but I got some issues.
**unknwn func name b1(Did I miss sth?)**
 
Below is my code:
package main

type B struct{}

func (this B)b0(s string) string {
	return this.b1(s)
}

func (this B)b1(s string) string {
	return s
}

**test**
func TestB0(t *testing.T){
	var obj B
	monkey.PatchInstanceMethod(reflect.TypeOf(obj), "b1", func(_ B,s string) string {
		return "changed"
	})
	assert.Equal(t,"changed",obj.b0("unchanged"))
	monkey.UnpatchInstanceMethod(reflect.TypeOf(obj), "b1")
}

**result**

panic: unkown method b1

**Comment by bouk** [comment]
Just type b1 without the quotes, you need to pass a function pointer, not a string

**Comment by soldiershen** [comment]
It needs a string type 

func PatchInstanceMethod(target reflect.Type, **methodName string,** replacement interface{}) *PatchGuard {
	m, ok := target.MethodByName(methodName)
	if !ok {
		panic(fmt.Sprintf("unkown method %s", methodName))
	}
	r := reflect.ValueOf(replacement)
	patchValue(m.Func, r)

	return &PatchGuard{m.Func, r}
}
