### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by ckstettler** [bouk/monkey#9]
Kind of a shame.  Are you stating this because there are much better ways?  I am coming from a java/python background and the golang mocking seems to be difficult unless I am missing something.  The mocking tools seem to be focused on only interfaces which is a good pattern to follow, but not all tools follow the pattern and therefore are difficult to mock.  Your tool solved my problem nicely, but I will keep digging for "the better" way.

**Comment by bouk** [comment]
Yeah, in Go you should be using interfaces for mocking. If you want to mock other tools, I would suggest wrapping them into an interface yourself and then writing a mock for that interface. That way you separate out this dependency cleanly, making sure you're not mixing concerns too much.
